variable "availability_zones" {
  description = "The availability zones to use"
  type        = list(string)
  default     = ["us-east-1a", "us-east-1b", "us-east-1c"]
}

variable "internal" {
  description = "Flag to determine if the several AWS resources are public (intended for external access, public internet) or private (only intended to be accessed within your AWS VPC or avaiable with other means, a transit gateway for example)."
  type        = bool
  default     = false
}

variable "owner" {
  description = "The owner of the infrastructure"
  type        = string
  default     = "skylight"
}

# Manually update to set the version you want to run
variable "phdi_version" {
  description = "dibbs-ecr-viewer container image version"
  type        = string
  default     = "5.0.0"
}

variable "dibbs_config_name" {
  description = "The name of the DIBBS configuration"
  type        = string
  default     = "AWS_PG_NON_INTEGRATED"
}

variable "database_type" {
  description = "The type of database to use (postgresql or sqlserver or '')"
  type        = string
  default     = ""
}

variable "private_subnets" {
  description = "The private subnets"
  type        = list(string)
  default     = ["176.24.1.0/24", "176.24.3.0/24"]
}

variable "project" {
  description = "The project name"
  type        = string
  default     = "dibbs"
}

variable "public_subnets" {
  description = "The public subnets"
  type        = list(string)
  default     = ["176.24.2.0/24", "176.24.4.0/24"]
}

variable "region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

variable "vpc_cidr" {
  description = "The CIDR block for the VPC"
  type        = string
  default     = "176.24.0.0/16"
}

variable "route53_hosted_zone_id" {
  description = "The Route53 hosted zone ID"
  type        = string
  default     = ""
  sensitive   = true
}

variable "auth_provider" {
  description = "The authentication provider used. Either keycloak or ad."
  type        = string
  default     = ""
}

variable "auth_client_id" {
  description = "The application/client id used to idenitfy the client"
  type        = string
  default     = ""
}

variable "auth_issuer" {
  description = "Additional information used during authentication process. For Azure AD, this will be the 'Tenant Id'. For Keycloak, this will be the url issuer including the realm - e.g. https://my-keycloak-domain.com/realms/My_Realm"
  type        = string
  default     = ""
}

variable "auth_url" {
  description = "Optional. The full URL of the auth api. By default https://your-site.com/ecr-viewer/api/auth."
  type        = string
  default     = ""
}

variable "auth_session_duration_min" {
  description = "Duration in minutes before auto signout, defaults to 30 if not set"
  type        = string
  default     = ""
}

variable "secrets_manager_auth_secret_version" {
  description = "The secret containing the auth secret. This is used by eCR viewer to encrypt authentication. This can be generated by running `openssl rand -base64 32`."
  type        = string
  default     = ""
  sensitive   = true
}

variable "secrets_manager_auth_client_secret_version" {
  description = "The secret containing the auth client secret. This is the secret that comes from the authentication provider."
  type        = string
  default     = ""
  sensitive   = true
}

variable "secrets_manager_metadata_database_migration_secret_version" {
  description = "The secret containing the db migration secret. This is used by eCR viewer to allow database migrations."
  type        = string
  default     = ""
  sensitive   = true
}

variable "nbs_pub_key" {
  type        = string
  description = "The public key used to validate the incoming authenication for the eCR Viewer."
  default     = <<EOT
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAnlA1YmmbydxQdBh7DAq0
wUfsjR25eWZOB995mHclT3C46oLat3YLu70akLfoMXd9YcJe0d4q3sP7tS1J4QDO
IkfapvK3ClDJR2VUERTzR9yQ+1B1Sd+MSful/V3aP9L6wPRAJmsmziizUBz+X0oN
WTkGP/xi0F/IlyBfh2sk89JKKmgXSFbgDTD7+8L5WeRY5koR0KfDJLBcyerrcIPW
1FyD8RbkUH78yJXc+/ThXKBNpsDTvV0k/4zqLSADIEmhQFkW8oYOfF4ufBGSnGdZ
gPoWbKHtlK+m1sFWMq0hAtJsNKsJQocPAEO2NIxRCX4k6X9HfvCYVniDI4OdVz0V
jTF+galQDAybgtYc9ZN8ROpePDVkCANHzniBJFOwzv2yekreqdX7M399uLB+ztDX
Iz2RpZbGkgspl4TWvvB+eN64DJykmExImIw1nFc/6AVd3jhKSnCrckpGV3XaF8lW
WMA6au0RXjmRa4YxO/uQbFZeFkM7aQtQK/CxqdBfG0SACcIMwU2S7Kb5+c9Hs687
LI8j7j0oVyCiAyJ44Mi70i4A2GedyM6kzdixTmszin+c4tT8mYjmEMpJle6GLBIa
aqEy3CVEqecFIo4ypfoo4GjTqvv/JjtxwBl1FPC+HzFkOjSoLbrDmn64NnQhXlC9
kd+ONf43CmqDSTa3atSFq4sCAwEAAQ==
-----END PUBLIC KEY-----
EOT
}

variable "ssh_key_name" {
  description = "The name of the SSH key to use for the instances"
  type        = string
  default     = ""
}

variable "ecr_processing_timeout" {
   type        = string
  description = "Set processing timeout length in ms,if not set defaults to 900000ms (15min)"
  default     = "" 
}