name: Deploy to ECS

on:
  push:
    branches:
      - 1611-create-elastic-container-service

permissions:
  id-token: write
  contents: read
jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform/implementation/ecs
    steps:
      - name: Check Out Changes
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: githubECSDeploymentWorkflow
          aws-region: us-east-1

      - name: Load variables
        env:
          ENVIRONMENT: dev
          BUCKET: infra-tfstate-alis-default-aizwjxuh
          DYNAMODB_TABLE: infra-tfstate-lock-alis-default-aizwjxuh
          REGION: us-east-1
          OWNER: alis
          PROJECT: infra
        shell: bash
        run: |
          echo "ENVIRONMENT=$ENVIRONMENT" >> .env
          echo "BUCKET=$BUCKET" >> .env
          echo "DYNAMODB_TABLE=$DYNAMODB_TABLE" >> .env
          echo "REGION=$REGION" >> .env
          echo "owner = \"$OWNER\"" >> $ENVIRONMENT.tfvars
          echo "project = \"$PROJECT\"" >> $ENVIRONMENT.tfvars
          echo "region = \"$REGION\"" >> $ENVIRONMENT.tfvars

      - name: Terraform
        run: |
          # ./ecs.sh -e dev --ci