name: Trigger Dev Deploy or Plan
run-name: Trigger Dev ${{ github.event.client_payload.event_type }} for ${{ github.event.client_payload.workspace }}${{ github.event.client_payload.dev_id }}:${{ github.event.client_payload.version }} by @${{ github.actor }}

on:
  repository_dispatch:
    types: [trigger-dev-deploy, trigger-dev-plan]

jobs:
  trigger_dev_deploy:
    name: Trigger Dev Deploy
    if: ${{ github.event.client_payload.event_type == 'trigger-dev-deploy' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Changes
        uses: actions/checkout@v4

      - name: Trigger Dev Deploy
        uses: ./deployment_apply.yaml
        with:
          workspace: dev
          id: ${{ github.event.client_payload.dev_id }}
          dibbs-ecr-viewer-version: ${{ github.event.client_payload.version }}
          dibbs-ecr-viewer-config-name: ${{ github.event.client_payload.config_name }}
          dibbs-ecr-viewer-auth-provider: ad
          tf_branch: ${{ github.event.client_payload.tf_branch != '' && github.event.client_payload.tf_branch || 'main' }}
          config_name: ${{ github.event.client_payload.config_name }}

  trigger_dev_plan:
    name: Trigger Dev Plan
    if: ${{ github.event.client_payload.event_type == 'trigger-dev-plan' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Changes
        uses: actions/checkout@v4

      - name: Trigger Dev Plan
        uses: ./deployment_plan.yaml
        with:
          workspace: dev
          id: ${{ github.event.client_payload.dev_id }}
          dibbs-ecr-viewer-version: ${{ github.event.client_payload.version }}
          dibbs-ecr-viewer-config-name: ${{ github.event.client_payload.config_name }}
          dibbs-ecr-viewer-auth-provider: ad
          tf_branch: ${{ github.event.client_payload.tf_branch != '' && github.event.client_payload.tf_branch || 'main' }}
          config_name: ${{ github.event.client_payload.config_name }}
